import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'ApplyAgent Terms of Service — rules and guidelines for using our platform.',
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <h1 className="mb-2 text-3xl font-bold">Terms of Service</h1>
      <p className="mb-8 text-sm text-muted-foreground">Last updated: April 6, 2026</p>

      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p>By accessing or using ApplyAgent (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">2. Description of Service</h2>
          <p>ApplyAgent is an AI-powered career tools platform that provides job posting evaluation, resume generation, cover letter creation, application tracking, and related career services. The Service uses artificial intelligence to analyze job descriptions and generate personalized career documents.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">3. Accounts</h2>
          <p>You must create an account to use the Service. You are responsible for maintaining the security of your account credentials. You must provide accurate and complete information during registration. You must be at least 18 years old to use the Service.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">4. Credits and Payment</h2>
          <p>The Service operates on a credit-based system. New accounts receive 3 free uses (one-time, non-renewable) that can be applied to any feature. Additional credits may be purchased through our billing page. All purchases are processed securely through Stripe.</p>
          <p className="mt-2"><strong>Refunds:</strong> Credit purchases are generally non-refundable. If you experience a technical issue that prevents you from using purchased credits, contact us within 14 days of purchase at <a href="mailto:support@applyagent.ca" className="text-primary hover:underline">support@applyagent.ca</a> and we will review your request on a case-by-case basis.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-6">
            <li>Use the Service for any unlawful purpose</li>
            <li>Submit false, misleading, or fraudulent information</li>
            <li>Attempt to gain unauthorized access to other accounts or systems</li>
            <li>Use automated scripts or bots to access the Service</li>
            <li>Resell, redistribute, or commercially exploit generated content without authorization</li>
            <li>Interfere with or disrupt the Service or its infrastructure</li>
            <li>Reverse-engineer or attempt to extract source code from the Service</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">6. AI-Generated Content</h2>
          <p>Content generated by the Service (evaluations, resumes, cover letters) is produced using artificial intelligence. While we strive for accuracy, AI-generated content may contain errors or inaccuracies. You are responsible for reviewing and verifying all generated content before use. The Service is a tool to assist your job search, not a replacement for professional career advice.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">7. Intellectual Property</h2>
          <p>You retain ownership of all content you submit to the Service (resumes, job descriptions, etc.). You grant us a limited license to process this content for the purpose of providing the Service. Content generated by the Service for your use belongs to you.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">8. Limitation of Liability</h2>
          <p>The Service is provided &quot;as is&quot; without warranties of any kind, express or implied. ApplyAgent shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to loss of employment opportunities, income, or data.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">9. Account Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these Terms. You may delete your account at any time through your account settings. Upon termination, your data will be deleted in accordance with our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">10. Changes to Terms</h2>
          <p>We may update these Terms from time to time. We will notify you of material changes by posting the updated Terms on this page. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">11. Governing Law</h2>
          <p>These Terms are governed by the laws of the Province of Manitoba, Canada. Any disputes shall be resolved in the courts of Manitoba, Canada.</p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">12. Contact</h2>
          <p>Questions about these Terms? Contact us at <a href="mailto:support@applyagent.ca" className="text-primary hover:underline">support@applyagent.ca</a>.</p>
        </section>
      </div>

      <div className="mt-12 border-t pt-6 text-center">
        <Link href="/" className="text-sm text-primary hover:underline">Back to home</Link>
      </div>
    </div>
  )
}
